---
# handlers file for slacko

- name: "enable mongodb"
  systemd: 
    name: mongodb
    state: started
    enable: yes

- name: "Start slacko-api.service" 
  systemd: 
    name: slacko-api.service
    state: started
    enable: yes  