---
# tasks file for slacko

- name: repo clone git
  git:
    repo: https://github.com/LeonardoDG2084/iaac_slacko-api
    dest: /opt
    separate_git_dir: /opt/ansible-examples.git

- name: instalando mongoDB
  apt:
    name: mongodb
    state: present
    update_cache: yes
  notify:
    - restart.mongodb

- name: instalando python requirements
  pip:
    requirements: /opt/requeriments.txt

- name: criando diretorio slacko-api
  file: 
    path: "{{ path_api }}"
    state: directory 
    owner: root
    group: root 
    mode: 0755   

- name:  copiando arquivos para o diretorio
  copy:
    src: "{{ item }}"
    dest: "{{ path_api }}"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  with_items:
    - /opt/main.py  

- name: Copiar script em service
  copy:
    src: templates/slacko-api.service
    dest: /etc/systemd/system
    owner: root
    group: root

  
- name: 'copiando arquivo conf para o diretorio'
  template:
    src: templates/slacko-api.sh
    dest: "{{ path_api }}"
    owner: root
    group: root
    mode: 0755 
 

- name: 'iniciando serviço'
  template:
    src: slacko-api.service
    dest: '{{ service_slacko }}'
    owner: root
    group: root
  notify:
    - copy.service
    - start.service
